slog:
  env: "local"   # Режим логирования (local, dev, prod)
  file: ""       # Файл для логов (пусто = stdout)

grpc:
  addr: ""  # Интерфейс прослушивания
  port: 8082       # Порт сервера

sub_pub:
  subject_buffer: 8        # Буфер сообщений темы
  subscription_buffer: 32  # Буфер подписки
  close_timeout: 1m        # Таймаут завершения